<?php

/** @var $viewModel Kravchuk\ModuleAdder\ViewModel\ProductSaleViewModel */

$viewModel = $block->getViewModel();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productId = $objectManager->get('Magento\Catalog\Model\Session')->getData('last_viewed_product_id');
$product = $objectManager->get('Magento\Catalog\Model\Product')->load($productId);


$regularPrice = $product->getPriceInfo()->getPrice('regular_price')->getMinRegularAmount()->getValue();
$finalPrice = $product->getFinalPrice();

$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
$currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode);
$currencySymbol = $currency->getCurrencySymbol();


?>

<div class='discount-box'>
    <span class="discount">
        <?php

            $sale = 0;
            if ($regularPrice > $finalPrice) {
                $sale = ($regularPrice - $finalPrice);
            }

            if ($sale > 0) echo " - save " . $currencySymbol . number_format((float)$sale, 2, '.', '');
            else echo "";

        ?>
    </span>
</div>
