<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>

<div class="copyright">
    <address class="copyright-address">
        <strong>THE IRISH STORE</strong>
        <div class="address-suite">Suite 6.</div>
        <div class="address-street">7 Upper O'Connell Street, Dublin 1, Ireland</div>
    </address>
    <div class="copyright-contact">
        <div>
            <strong>USA/CANADA:</strong>
            <a title="Call Us" href="tel: 18007075037" class="contact-USA">1800 707 5037 (toll free to Ireland)</a>
        </div>
        <div>
            <strong>International:</strong>
            <a title="Call Us" href="tel: +35318611590" class="contact-international">+353 186 11 590</a>
        </div>
        <div>
            <strong>Email:</strong>
            <a title="Contact Us" href="mailto: info@theirishstore.com" class="contact-mail">info@theirishstore.com</a>
        </div>
    </div>

    <div class="copyright-payment">
        <strong>100% SECURE SHOPPING CART</strong>
        <div class="payment-providers"></div>
    </div>
</div>
