<?php

/**
 * @var \Magento\Framework\View\Element\Template $block
 */

?>

<div class="header-text">
    <a class="header-text--link" href="#" title="Delivery Information">Extended 6 Month Free Returns</a>
    <div class="my-account">My Account</div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(".my-account").on('click', function(event){
            $(event.target).toggleClass("active");
            if($(event.target).hasClass("active"))
                $(".panel.header .header.links").css("visibility", "visible");
            else $(".panel.header .header.links").css("visibility", "hidden");
        });
    });


</script>

